[package] 
name = "cpp_math"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"] 

[package.host-dependencies]
cmake = "3.20.*"   
nanobind = "2.4.*" 
python = "3.12.*"
